import { Routes } from '@angular/router';
import { AuthenticationComponent } from './pages/authentication/authentication.component';
import { OtpComponent } from './pages/otp/otp.component';
import { EmailConfirmationComponent } from './pages/email-confirmation/email-confirmation.component';
import { AdSelectionComponent } from './pages/ad-selection/ad-selection.component';
import { HomeComponent } from './pages/home/home.component';
import { ProfileComponent } from './pages/profile/profile.component';
import { MyTicketsComponent } from './pages/my-tickets/my-tickets.component';
import { TicketDetailsComponent } from './pages/ticket-details/ticket-details.component';
import { ReportComponent } from './pages/report/report.component';
import { OverviewComponent } from './pages/overview/overview.component';
import { AgreementComponent } from './pages/agreement/agreement.component';
import { AboutComponent } from './pages/about/about.component';
import { TermsComponent } from './pages/terms/terms.component';
import { PrivacyComponent } from './pages/privacy/privacy.component';
import { NoAdComponent } from './pages/no-ad/no-ad.component';
import { CreateAdComponent } from './pages/create-ad/create-ad.component';
import { BuyTicketComponent } from './pages/buy-ticket/buy-ticket.component';
import { CreateAdSuccessComponent } from './pages/create-ad-success/create-ad-success.component';
import { PaymentComponent } from './pages/payment/payment.component';
import { VerificationComponent } from './pages/verification/verification.component';
import { FairDealPolicyComponent } from './pages/fair-deal-policy/fair-deal-policy.component';

export const routes: Routes = [
    { path: '', component: HomeComponent },
    { path: 'overview', component: OverviewComponent },
    { path: 'agreement', component: AgreementComponent },
    { path: 'about', component: AboutComponent },
    { path: 'terms', component: TermsComponent },
    { path: 'privacy', component: PrivacyComponent },
    { path: 'new-ad/success', component: CreateAdSuccessComponent },
    { path: 'new-ad/:adType?', component: CreateAdComponent },
    { path: 'login', component: AuthenticationComponent },
    { path: 'otp', component: OtpComponent },
    { path: 'email-confirmation', component: EmailConfirmationComponent },
    { path: 'ad-selection', component: AdSelectionComponent },
    { path: 'profile', component: ProfileComponent },
    { path: 'my-tickets', component: MyTicketsComponent },
    { path: 'ticket-details', component: TicketDetailsComponent },
    { path: 'report', component: ReportComponent },
    { path: 'no-ad', component: NoAdComponent },
    { path: 'buy-ticket/:ticketId', component: BuyTicketComponent },
    { path: 'payment', component: PaymentComponent },
    { path: 'verification', component: VerificationComponent },
    { path: 'fair-deal-policy', component: FairDealPolicyComponent },
    { path: '**', redirectTo: ''}
];     